#!/bin/bash

# Everything has to succeed
set -o errexit
set -o nounset

# TODO: rename to glue or yarn or something
# unyarn
create() {
  bin/create.py "$@"
}

py-deps() {
  bin/py_deps.py "$@"
}

bas() {
  _tmp/deps/bas.sh "$@"
}

package-manifest() {
  # Standalone scripts.
  cat <<EOF
Package
bin/create.py bin/create
bin/tin.sh bin/tin
bin/py_deps.py bin/py-deps
bin/hg-info.sh bin/hg-info
EOF

  # Crawl deps.  TODO: docopt.
  PYTHONPATH=.:_tmp/deps/docopt-master py-deps bin.multi

  # Python stub
  bas python-stub multi.py >_tmp/multi
  chmod +x _tmp/multi
  echo _tmp/multi bin/multi 

  # Package.stamp
  bas make-stamp Package >_tmp/Package.stamp
  echo _tmp/Package.stamp Package.stamp
}

Build() {
  # Everything here goes to stderr, so we don't have to redirect.
  package-manifest | create --out $CDI_OUT/tree-tools.tar.gz --no-prelude

  poly build doc/
}

# not called 'test' 
Test() {
  # TODO: need a tool that runs all the functions that start with test-* in a
  # shell script?  Or maybe just ./all?
  ./tin-test.sh smoke-test
  ./run.sh all-unit-tests
}

Deploy() {
  # TODO: Use CDI_HG_REVISION
  #local version=$CDI_HG_REVISION

  local version=0.1

  local name=tree-tools-$version.tar.gz
  scp $CDI_OUT/tree-tools.tar.gz $PBI_DEPLOY_DEST/tree-tools/$name
  bas metadata-line $name >> $PBI_DEPLOY_DEST/tree-tools/Index.txt
}

"$@"
