#!/bin/bash

# Everything has to succeed
set -o errexit
set -o nounset
set -o pipefail

py-deps() {
  bin/py_deps.py "$@"
}

multi() {
  bin/multi.py "$@"
}

package-manifest() {
  # Standalone scripts.
  cat <<EOF
Package
bin/py_deps.py bin/py-deps
bin/hg-info.sh bin/hg-info
EOF

  # Crawl deps.  TODO: docopt.
  PYTHONPATH=.:_tmp/deps/docopt-master py-deps bin.multi

  # Python stub
  basisc python-stub multi.py >_tmp/multi
  chmod +x _tmp/multi
  echo _tmp/multi bin/multi 

  # Package.stamp
  basisc echo-package-and-stamp tree-tools $CDI_HG_REVISION
}

Build() {
  # Everything here goes to stderr, so we don't have to redirect.
  package-manifest | multi tar $CDI_OUT/tree-tools.tar.gz

  poly build doc/
}

# not called 'test' 
Test() {
  # TODO: need a tool that runs all the functions that start with test-* in a
  # shell script?  Or maybe just ./all?
  ./tin-test.sh smoke-test
  ./run.sh all-unit-tests
}

Deploy() {
  local version=$CDI_HG_REVISION
  local name=tree-tools.$version.tar.gz
  scp $CDI_OUT/tree-tools.tar.gz $PBI_DEPLOY_DEST/tree-tools/$name
  basisc metadata-line $name >> $PBI_DEPLOY_DEST/tree-tools/Index.txt
}

"$@"
